nimble c --app:lib ^
    --out:dist/pocketsocket_server.pyd ^
    --threads:on ^
    --tlsEmulation:off ^
    -d:lto ^
    --mm:arc ^
    -d:useMalloc ^
    -d:release ^
    --opt:speed ^
    -d:strip ^
    --passL:-static src/pocketsocketpkg/pocketsocket_server.nim
